# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_1; end
module ::Anonymous_Delegator_2; end
module ::Anonymous_Delegator_4; end
module Kramdown::Converter::Kramdown::Utils::Configurable; end
module YARD::Logger; end
